name: Propagate Resume Updates

on:
  push:
    paths:
      - "resume.tex"
      - ".github/workflows/main.yml"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_banner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: LaTeX PDF Compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: gha-notice.tex
      
      - name: Save GitHub Banner
        uses: actions/upload-artifact@v2
        with:
          name: github_banner
          path: ./gha-notice.pdf
          
          
  build_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
          
      - name: LaTeX PDF Compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
            
      - name: Install ImageMagick & GhostScript
        run: |
              sudo apt-get install imagemagick
              sudo apt-get install ghostscript
              sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
              sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
            
      - name: Generate Resume PNG Image 
        run: convert -verbose -density 500 -background white -alpha remove -alpha off resume.pdf -quality 100 resume.png
        
      - name: Save Resume Resources
        uses: actions/upload-artifact@v2
        with:
          name: resume_resources
          path: ./[resume]*
        

  update_resume_repository:
    runs-on: ubuntu-latest
    needs: build_resources
    steps:      
      - uses: actions/download-artifact@v2
        with:
          name: resume_resources
        
      - name: Update Image Preview
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "resume.png"
          destination_repo: "thienlongtran/resume"
          destination_branch: "master"
          user_email: "tltran5@uno.edu"
          user_name: "thienlongtran"
            
      - name: Update PDF File
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "resume.pdf"
          destination_repo: "thienlongtran/resume"
          destination_branch: "master"
          user_email: "tltran5@uno.edu"
          user_name: "thienlongtran"
          
      - name: Update LaTeX File
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "resume.tex"
          destination_repo: "thienlongtran/resume"
          destination_branch: "master"
          user_email: "tltran5@uno.edu"
          user_name: "thienlongtran"


  update_current_resume_gdrive:
    runs-on: ubuntu-latest
    needs: build_resources
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: resume_resources

      - name: Update Current Resume (Google Drive)
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "resume.pdf"
          folderId: ${{ secrets.CURRENT_RESUME_GDRIVE_FOLDERID }}
          name: "ThienTran_Current_Resume.pdf"
          overwrite: "true"
          
          
  upload_to_resume_history_gdrive:
    runs-on: ubuntu-latest
    needs: build_resources
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: resume_resources
          
      - name: Set Current Date and Time
        run: echo "CURRENT_DATE_AND_TIME=$(TZ=America/New_Orleans date +'%D_%H:%M:%S')" >> ${GITHUB_ENV}

      - name: Upload to Resume History (Google Drive)
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "resume.pdf"
          folderId: ${{ secrets.RESUME_HISTORY_GDRIVE_FOLDERID }}
          name: "ThienTran_${{ env.CURRENT_DATE_AND_TIME }}.pdf"
          

  update_personal_website:
    runs-on: ubuntu-latest
    needs: [build_banner, build_resources]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: resume_resources
      
      - uses: actions/download-artifact@v2
        with:
          name: github_banner
      
      - name: Add GitHub Actions Notice to Resume PDF
        run: |
              sudo apt-get install pdftk
              pdftk *.pdf cat output Thien_Tran_Resume.pdf

      - name: Pushing Resume PDF to Website Repository
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "Thien_Tran_Resume.pdf"
          destination_repo: "thienlongtran/thienlongtran.github.io"
          destination_folder: "assets"
          destination_branch: "master"
          user_email: "tltran5@uno.edu"
          user_name: "thienlongtran"
